---
# - name: Copy Jenkins key pair key
#   copy:
#     src=../files/github
#     dest=/home/{{ web_default_user }}/.ssh/
#     owner={{ web_default_user }}
#     group={{ web_default_user }}
#     mode=0600

# - name: Template out SSH Config
#   template:
#     src=../templates/ssh_config.j2
#     dest=/home/{{ web_default_user }}/.ssh/config
#     owner='{{ web_default_user }}'
#     group='{{ web_default_user }}'
#     mode=0644

- name: Create Web Stack Directories
  file:
    path={{ h4_repo_path }}/../data/graphs
    owner={{ web_default_user }}
    group={{ web_default_user }}
    state=directory

- name: Check if code base already exists
  sudo: no
  shell: git log --pretty=oneline -n 10
  ignore_errors: yes
  register: h4_repo_exists
  args:
    chdir: '{{ h4_repo_path }}'

- name: Clone Tetration '{{ h4_repo_name }}' Git Repo
  when: h4_repo_exists | failed
  sudo: no
  shell: git clone '{{ h4_source_repo }}' '{{ h4_repo_path }}'
  register: result
  until: result.rc == 0
  retries: '{{ default_git_num_retries }}'
  delay: '{{ default_git_retry_delay }}'
  environment: "{{ proxy_env }}"

- name: Update if '{{ h4_repo_name }}' repo already exists
  when: h4_repo_exists | success
  sudo: no
  shell: '{{ item }}'
  register: result
  with_items:
    - git fetch -p --tags
    - git gc --prune
    # - GIT_LFS_SKIP_SMUDGE=1 git reset --hard origin/{{ base_branch }}
    # - git lfs pull
  args:
    chdir: '{{ h4_repo_path }}'
  until: result.rc == 0
  retries: '{{ default_git_num_retries }}'
  delay: '{{ default_git_retry_delay }}'
  environment: "{{ proxy_env }}"
