
pipeline {
  agent {
    label 'docker'
  }
  parameters {
    string(name: 'BUILD_BRANCH', defaultValue: 'master', description: 'Build Branch')
    string(name: 'VERSION', defaultValue: '1.0.0', description: 'RPM Version')
    string(name: 'TAG', defaultValue: 'latest', description: 'Docker Image Tag')
    string(name: 'DEPLOY_ANSIBLE_VERSION', description: 'image version', defaultValue: '3.2.1.1.devel')
  }
  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr:'20'))
    timeout(time: 50, unit: 'MINUTES')
  }
  stages {
    stage('Notify') {
      steps {
        sh """
          curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#FFFF00", "text":":rocket: STARTED: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
        """
      }
    }
    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: "*/${params.DEPLOY_ANSIBLE_VERSION}"]],
          doGenerateSubmoduleConfigurations: false,
          extensions: [
            [$class: 'CleanBeforeCheckout'],
            [$class: 'PruneStaleBranch'],
            [$class: 'CloneOption', depth: 0, noTags: false, reference: '', shallow: true, timeout: 30]
           ],
          submoduleCfg: [],
          userRemoteConfigs: [[
            url: 'git@github.com:TetrationAnalytics/deploy-ansible.git',
            refspec: '+refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/remotes/origin/tags/*'
          ]]
        ])

        checkout([
          $class: 'GitSCM',
          branches: [[name: "*/${params.BUILD_BRANCH}"]],
          doGenerateSubmoduleConfigurations: false,
          extensions: [
            [$class: 'CleanBeforeCheckout'],
            [$class: 'PruneStaleBranch'],
            [$class: 'CloneOption', depth: 0, noTags: false, reference: '', shallow: true, timeout: 30]
           ],
          submoduleCfg: [],
          userRemoteConfigs: [[
            url: 'git@github.com:TetrationAnalytics/url-to-pdf-api.git',
            refspec: '+refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/remotes/origin/tags/*'
          ]]
        ])
      }
    }
    stage('Build RPM and Docker Image') {
      steps {
        sh """
          cd builder-setup && make BUILD_BRANCH=${params.BUILD_BRANCH} VERSION=${params.VERSION} -f Makefile.docker build &&  docker image ls
        """
      }
    }
    stage('Deliver') {
      steps {
        sh """
          ls docker/ && cd builder-setup && make deliver VERSION=${params.VERSION} TAG=${params.TAG}
        """
      }
    }
  }
  post {
    success {
      sh """
        curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#00FF00", "text":":sunny: SUCCESSFUL: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
      """
    }
    failure {
      sh """
        curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#FF0000", "text":":bomb: FAILED: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
      """
    }
  }
}
