#
# To build a specific hash:
# ----------
#
# ansible-playbook -i inventory/<site> playbooks/pdf_printer_build_pkgr.yml -v -s
# --extra-vars "build_hash=cf4c2dc4332d2415c577a09ffff8c2cf0169426d build_latest=false"
#
# To build a specific branch:
# ----------
#
# ansible-playbook -i inventory/<site> playbooks/pdf_printer_build_pkgr.yml -v -s
# --extra-vars "build_branch=my_new_feature_branch"
#
# To build latest on master:
# ----------
#
# ansible-playbook -i inventory/<site> playbooks/pdf_printer_build_pkgr.yml -v -s
#
---
- hosts: pdf_printer_builder
  vars:
    local_user: "{{ lookup('env', 'USER') }}"
    local_hostname: "{{ lookup('pipe', 'hostname') }}"
    notify: false

  roles:
    - ../roles/base_pkgs
    - ../roles/pkgr_build_pdf_printer
